---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
  namespace: development
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: inventory-service
          image: 593793049094.dkr.ecr.eu-north-1.amazonaws.com/dev-inventory-service:37df72b2d7e60f7090b7f288b77a0c60285605fb
#          imagePullPolicy: Never - This is commented out to allow Kubernetes to pull the image from ECR. If you want to use a local image, uncomment this line and ensure the image is built locally.
          ports:
            - containerPort: 8088