---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: development
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
