apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: development
  labels:
    app: localstack
spec:
  type: NodePort # Change to NodePort if you need access from outside the cluster
  ports:
    - port: 4566
      targetPort: 4566
      name: gateway
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:2.3
          ports:
            - containerPort: 4566
          env:
            - name: DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            - name: SERVICES
              value: "sns,sqs,ses,dynamodb" # List services you want to enable
            - name: DEBUG
              value: "1"
            - name: DOCKER_HOST
              value: "unix:///var/run/docker.sock"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock