---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  namespace: development
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: payment-service
          image: .dkr.ecr..amazonaws.com/dev-payment-service:7738e01d80d118243ad990a0399fd18f02b46d34
#          imagePullPolicy: Never - This is commented out to allow Kubernetes to pull the image from ECR. If you want to use a local image, uncomment this line and ensure the image is built locally.
          ports:
            - containerPort: 8086