---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: development
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 593793049094.dkr.ecr.eu-north-1.amazonaws.com/dev-order-service:latest
#          imagePullPolicy: Never  This is commented out to allow Kubernetes to pull the image from ECR. If you want to use a local image, uncomment this line and ensure the image is built locally.
          ports:
            - containerPort: 8085
          env:
            - name: LOCALSTACK_ENDPOINT
              value: http://localstack:4566
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SNS_TOPIC_ARN
              value: arn:aws:sns:us-east-1:000000000000:order-topic
            - name: PAYMENT_SERVICE_URL
              value: http://payment-service:8086
            - name: INVENTORY_SERVICE_URL
              value: http://inventory-service:8088
            - name: JAVA_TOOL_OPTIONS
              value: -Xmx640m -Xms256m -XX:MaxMetaspaceSize=128M -XX:MaxDirectMemorySize=128M -XX:ReservedCodeCacheSize=128M -XX:+PrintCodeCache