---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/gorantlapc/platform-gitops.git
    targetRevision: master
    path: apps
#    temporary fix to sync all apps but should be removed when we have one app per service
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true