---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/gorantlapc/platform-gitops.git
    targetRevision: master
    path: clusters/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true