---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: development
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: api-gateway
          image: 593793049094.dkr.ecr.eu-north-1.amazonaws.com/dev-api-gateway:938efbc4e0bf4a26386d89e3590ea58d1570e49d
#          imagePullPolicy: Never - This is commented out to allow Kubernetes to pull the image from ECR. If you want to use a local image, uncomment this line and ensure the image is built locally.
          ports:
            - containerPort: 8084
          env:
            - name: PAYMENT_SERVICE_URL
              value: http://payment-service:8086
            - name: INVENTORY_SERVICE_URL
              value: http://inventory-service:8088
            - name: ORDER_SERVICE_URL
              value: http://order-service:8085
            - name: USER_SERVICE_URL
              value: http://user-service:8082